channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor
  - goosefem
  - gmatelastoplasticqpot

  # optional dependencies
  # - xsimd

  # build tools
  - cmake
  - ninja
  - setuptools_scm

  # Python API
  - python
  - numpy
  - xtensor-python
  - pybind11
  - pyxtensor

  # run tests
  - catch2
  - python-goosefem
  - python-gmattensor
  - python-gmatelastoplasticqpot
  - numpy

