channels:
  - conda-forge
dependencies:
  # dependencies
  - gmatelastoplasticqpot
  - goosefem
  - xtensor

  # optional dependencies
  - xsimd

  # build tools
  - cmake

  # Python API
  - python
  - pyxtensor

  # to run tests
  - catch2
  - fmt
  - goosefem
  - python-goosefem
  - python-gmattensor
  - python-gmatelastoplasticqpot
  - numpy

