name: CI • Python

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: ${{ matrix.runs-on }} • x64 ${{ matrix.args }}
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        cache-env: true
        extra-specs: |
          python-gmattensor
          python-goosefem
          python-gmatelastoplasticqpot
          sel(linux): cxx-compiler
          sel(win): clang_win-64

    - name: Build and install Python module
      run: python -m pip install . -vv

    - name: Run Python tests
      working-directory: tests
      run: |
        python basic.py
        python Generic2d.py
        python UniformMultiLayerIndividualDrive2d.py
        python UniformMultiLayerLeverDrive2d.py
        python UniformSingleLayer2d.py
        python UniformSingleLayer2d_LocalTriggerFineLayer.py
