name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  default-shell:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment "test"
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: environment.yaml
        activate-environment: test
        auto-activate-base: false

    - name: Extending conda environment for testing
      run: |
        conda env update --file environment_test.yaml
        conda env update --file environment_examples.yaml

    - name: Configure using CMake (also compile examples)
      if: runner.os == 'Linux'
      run: cmake . -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON

    - name: Configure using CMake (skip compilation of examples)
      if: runner.os != 'Linux'
      run: cmake . -DBUILD_TESTS=ON

    - name: Build C++ tests & examples
      run: cmake --build .

    - name: Run C++ tests
      run: cmake --build . --target "RUN_ALL_TESTS"

    - name: Build and install Python module
      run: |
        python setup.py build
        python setup.py install

    - name: Run Python tests
      run: python test/UniformSingleLayer2d_LocalTriggerFineLayer.py
