name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            config: -DBUILD_TESTS=1 -DBUILD_EXAMPLES=1 -DBUILD_DOCS=1
            conda: environment.yaml
            prop: tests, examples & docs
          - runs-on: macos-latest
            config: -DBUILD_TESTS=1
            conda: .ci_environment_tests.yaml
            prop: tests
          - runs-on: windows-latest
            config: -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTS=1
            conda: .ci_environment_tests.yaml
            prop: tests

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ${{ matrix.conda }}
        environment-name: myenv

    - name: Install clang
      if: runner.os == 'Windows'
      run: micromamba install -c conda-forge clang_win-64 ninja

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=0.0" >> $GITHUB_ENV

    - name: Configure using CMake
      run: cmake -Bbuild ${{ matrix.config }}

    - name: Build C++ ${{ matrix.prop }}
      working-directory: build
      run: cmake --build .

    - name: Run C++ ${{ matrix.prop }}
      working-directory: build
      run: ctest --output-on-failure

    - name: Build and install Python module
      run: python -m pip install . -vvv

    - name: Run Python tests
      working-directory: test
      run: python UniformSingleLayer2d_LocalTriggerFineLayer.py

    - name: Build doxygen-docs (error on warning)
      if: runner.os == 'Linux'
      working-directory: build
      run: make docs
